/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primaryColor: "#5B9895",
        hoverColor: "#477775",
        tagbg: "#D9D9D946",
        tagbg2: "#07070740",
        textColor: "#666c89",
        headingColor: "#1c1f35",
        featurebg: "#5AB2AF57",
        tbg: "#3BA19A90",
        yellowColor: "#FEB60D",
        testibg: "#F4F4F4",
        testibg2: "#091242",
        "nav-border": "#EBEAEA",
        "light-white": "#FAFAFB",
        "light-white-100": "#F1F4F5",
        "light-white-200": "#d7d7d7",
        "light-white-300": "#F3F3F4",
        "light-white-400": "#E2E5F1",
        "light-white-500": "#E4E4E4",
        gray: "#4D4A4A",
        "gray-100": "#3d3d4e",
        "black-100": "#252525",
        "primary-purple": "#9747FF",
        "gray-50": "#D9D9D9",
      },
      boxShadow: {
        menu: "0px 159px 95px rgba(13,12,34,0.01), 0px 71px 71px rgba(13,12,34,0.02), 0px 18px 39px rgba(13,12,34,0.02), 0px 0px 0px rgba(13,12,34,0.02)",
      },
      screens: {
        xs: "400px",
      },
      maxWidth: {
        "10xl": "1680px",
      },
      backgroundImage: {
        "hero-bg": "url('/hero-bg.jpg')",
        "whyus-bg": "url('/container-home-bg2.jpg')",
        mapbg: "url('/mapbg.png')",
        "contact-bg": "url('/truckcontact.jpg')",
        "service-bg": "url('/truckservice.jpg')",
        "aboutus-bg": "url('/truckabout.jpg')",
        "clients-bg": "url('/containerclients.jpg')",
        "team-bg": "url('/manteam.jpg')",
        "track-bg": "url('/boxtrack.jpg')",
        "track2-bg": "url('/containertrack.jpg')",
        "map-bg": "url('/mapbg2.png')",
        bluebg: "url('/bluegradient.png')",
        bluebgsm: "url('/bluegradientsm.png')",
        graybg: "url('/graygradient.png')",
        graybgsm: "url('/graygradientsm.png')",
      },
    },
  },
  plugins: [],
};
